"""Tests for hermes_managed.contracts — strict RuntimeAssignment parsing.

Covers the frozen contract decisions from the MVP plan (Task 6) and the P0
cross-language fix: the effective-policy checksum is SkillHub's
``PolicyChecksum.frame`` length-framed SHA-256, NOT canonical JSON.

Policy golden vectors are generated by the REAL SkillHub ``PolicyChecksum.java``
(see ``golden_policy_vectors/``) and embedded here as constants.  The policy
tests never use the Python framing function to produce an "expected" SHA — they
only read the fixed Java digests and assert the parser agrees.
"""

import dataclasses
import json
from pathlib import Path

import pytest

from hermes_managed.contracts import (
    ChecksumMismatchError,
    FieldTypeError,
    ManagedContractError,
    MissingRequiredFieldError,
    RuntimeAssignment,
    canonical_json_bytes,
    parse_runtime_assignment,
    sha256_hex,
)

# Canaries planted inside the manifest / policy.  No error message may contain them.
MANIFEST_CANARY = "MANIFEST_SECRET_CANARY_4f3a"
POLICY_CANARY = "POLICY_SECRET_CANARY_9c1b"


# --- policy golden vectors (authoritative Java output) ------------------------
# Each tuple: (mode, allowedModels, defaultModel, fallbackModels, localProviderAllowed,
#              policySha256, policyVersion, framed).
# Generated by tests/managed/golden_policy_vectors/GoldenVectorsMain.java using the
# verbatim SkillHub PolicyChecksum.java.  Vector "java_test_cross_check" equals the
# literal SHA asserted by SkillHub's EffectiveModelPolicyResolverTest.
GOLDEN_VECTORS = [
    {
        "id": "single_no_fallback_local_false",
        "mode": "ENTERPRISE_MANAGED",
        "allowedModels": ["enterprise/deepseek-chat"],
        "defaultModel": "enterprise/deepseek-chat",
        "fallbackModels": [],
        "localProviderAllowed": False,
        "policySha256": "5ea1e6720cc6dc3ef2cae5579c687dd98d80245bdf3a2ca89fb70e85c876899a",
        "policyVersion": "sha256:5ea1e6720cc6",
        "framed": "V18:ENTERPRISE_MANAGEDL1:V24:enterprise/deepseek-chatV24:enterprise/deepseek-chatL0:V5:false",
    },
    {
        "id": "multi_allowed_ordered_fallback_local_false",
        "mode": "ENTERPRISE_MANAGED",
        "allowedModels": ["enterprise/deepseek-chat", "enterprise/gpt-5"],
        "defaultModel": "enterprise/deepseek-chat",
        "fallbackModels": ["enterprise/gpt-5"],
        "localProviderAllowed": False,
        "policySha256": "22975c12f50e651138904b406b0c196fd2896c8c4b803020f8dc77ab74f6e2e9",
        "policyVersion": "sha256:22975c12f50e",
        "framed": "V18:ENTERPRISE_MANAGEDL2:V24:enterprise/deepseek-chatV16:enterprise/gpt-5V24:enterprise/deepseek-chatL1:V16:enterprise/gpt-5V5:false",
    },
    {
        "id": "local_true",
        "mode": "USER_SELECTABLE",
        "allowedModels": ["local/ollama-qwen", "openai/gpt-5"],
        "defaultModel": "local/ollama-qwen",
        "fallbackModels": ["openai/gpt-5"],
        "localProviderAllowed": True,
        "policySha256": "95e771d8e2771767aa6cc934d6ca3566bf1ccbc4160b9f11a958bda9ee5a67bb",
        "policyVersion": "sha256:95e771d8e277",
        "framed": "V15:USER_SELECTABLEL2:V17:local/ollama-qwenV12:openai/gpt-5V17:local/ollama-qwenL1:V12:openai/gpt-5V4:true",
    },
    {
        "id": "non_ascii_utf8_byte_length",
        "mode": "ENTERPRISE_MANAGED",
        "allowedModels": ["enterprise/中文模型", "enterprise/café"],
        "defaultModel": "enterprise/中文模型",
        "fallbackModels": ["enterprise/café"],
        "localProviderAllowed": False,
        "policySha256": "2cba6be3d718454ab863e91bd4439b69be2aafb014dd2e7c4b76982b4b18d18c",
        "policyVersion": "sha256:2cba6be3d718",
        "framed": "V18:ENTERPRISE_MANAGEDL2:V23:enterprise/中文模型V16:enterprise/caféV23:enterprise/中文模型L1:V16:enterprise/caféV5:false",
    },
    {
        "id": "java_test_cross_check",
        "mode": "USER_SELECTABLE",
        "allowedModels": ["openai/gpt-5", "anthropic/claude-sonnet"],
        "defaultModel": "anthropic/claude-sonnet",
        "fallbackModels": [],
        "localProviderAllowed": False,
        "policySha256": "c691e382c4f337ac5e93d492804200a4a4e1650cab6f11685556abeaef30901c",
        "policyVersion": "sha256:c691e382c4f3",
        "framed": "V15:USER_SELECTABLEL2:V12:openai/gpt-5V23:anthropic/claude-sonnetV23:anthropic/claude-sonnetL0:V5:false",
    },
]


def _golden_policy(vector: dict) -> dict:
    """Build a policy dict matching a golden vector (extra fields allowed)."""
    return {
        "mode": vector["mode"],
        "allowedModels": list(vector["allowedModels"]),
        "defaultModel": vector["defaultModel"],
        "fallbackModels": list(vector["fallbackModels"]),
        "localProviderAllowed": vector["localProviderAllowed"],
        "policyVersion": vector["policyVersion"],
        "policySha256": vector["policySha256"],
        "note": POLICY_CANARY,
    }


def _base_manifest() -> dict:
    return {
        "templateSlug": "reference-assistant",
        "displayName": "Reference Assistant",
        "version": "1.0.0",
        "modelPolicy": {
            "mode": "ENTERPRISE_MANAGED",
            "allowedModels": ["enterprise/deepseek-chat"],
            "defaultModel": "enterprise/deepseek-chat",
            "fallbackModels": [],
            "localProvider": {"allowed": False},
        },
        "workspace": {"roots": ["/workspace/reference"]},
        "tools": {"allowed": ["read_file"], "approvalRequired": ["read_file"]},
        "enterpriseSkills": [
            {
                "slug": "summarize",
                "files": [{"path": "SKILL.md", "content": MANIFEST_CANARY}],
            }
        ],
        "note": MANIFEST_CANARY,
    }


def _base_payload(**overrides) -> dict:
    manifest = _base_manifest()
    policy = _golden_policy(GOLDEN_VECTORS[0])
    payload = {
        "assignmentId": 20,
        "revision": 2,
        "templateId": 10,
        "versionId": 19,
        "templateSlug": "reference-assistant",
        "displayName": "Reference Assistant",
        "manifest": manifest,
        "manifestSha256": sha256_hex(canonical_json_bytes(manifest)),
        "effectiveModelPolicy": policy,
        "revoked": False,
        "revokedAt": None,
    }
    payload.update(overrides)
    return payload


class TestCanonicalJson:
    def test_keys_sorted_recursively_and_compact(self):
        a = {"b": {"d": 1, "c": 2}, "a": 3}
        b = {"a": 3, "b": {"c": 2, "d": 1}}
        assert canonical_json_bytes(a) == canonical_json_bytes(b)

    def test_compact_separators(self):
        assert canonical_json_bytes({"a": 1, "b": 2}) == b'{"a":1,"b":2}'

    def test_unicode_preserved_as_utf8(self):
        assert canonical_json_bytes({"k": "中文"}) == '{"k":"中文"}'.encode("utf-8")

    def test_sha256_hex_is_64_lowercase_hex(self):
        h = sha256_hex(b"")
        assert h == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        assert len(h) == 64


class TestParseValidAssignment:
    def test_populates_all_fields(self):
        assignment = parse_runtime_assignment(_base_payload())

        assert assignment.assignment_id == 20
        assert assignment.revision == 2
        assert assignment.template_id == 10
        assert assignment.version_id == 19
        assert assignment.template_slug == "reference-assistant"
        assert assignment.display_name == "Reference Assistant"
        assert assignment.manifest["templateSlug"] == "reference-assistant"
        assert assignment.manifest_sha256 == sha256_hex(
            canonical_json_bytes(_base_manifest())
        )
        assert assignment.effective_model_policy["policyVersion"] == "sha256:5ea1e6720cc6"
        assert assignment.revoked is False
        assert assignment.revoked_at is None

    def test_revoked_assignment_with_timestamp(self):
        payload = _base_payload(revoked=True, revokedAt="2026-07-12T10:00:00Z")
        assignment = parse_runtime_assignment(payload)
        assert assignment.revoked is True
        assert assignment.revoked_at == "2026-07-12T10:00:00Z"

    def test_revoked_at_defaults_to_none_when_absent(self):
        payload = _base_payload()
        payload.pop("revokedAt")
        assignment = parse_runtime_assignment(payload)
        assert assignment.revoked_at is None

    def test_assignment_is_frozen(self):
        assignment = parse_runtime_assignment(_base_payload())
        with pytest.raises(dataclasses.FrozenInstanceError):
            assignment.revision = 99  # type: ignore[misc]

    def test_unknown_top_level_fields_are_ignored(self):
        payload = _base_payload(extraServerField="ignore-me")
        assignment = parse_runtime_assignment(payload)
        assert assignment.revision == 2


@pytest.mark.parametrize(
    "field,value",
    [
        ("assignmentId", None),
        ("revision", None),
        ("templateId", None),
        ("versionId", None),
        ("templateSlug", None),
        ("displayName", None),
        ("manifest", None),
        ("manifestSha256", None),
        ("effectiveModelPolicy", None),
        ("revoked", None),
    ],
)
class TestMissingRequiredField:
    def test_missing_or_null_raises_without_leaking(self, field, value):
        payload = _base_payload()
        if value is None:
            del payload[field]
        else:
            payload[field] = value

        with pytest.raises((MissingRequiredFieldError, FieldTypeError)) as exc_info:
            parse_runtime_assignment(payload)

        message = str(exc_info.value)
        assert MANIFEST_CANARY not in message
        assert POLICY_CANARY not in message
        assert field.lower() in message.lower()


@pytest.mark.parametrize(
    "field,bad_value,expected",
    [
        ("assignmentId", "20", FieldTypeError),
        ("revision", "2", FieldTypeError),
        ("revision", 2.5, FieldTypeError),
        ("templateId", "10", FieldTypeError),
        ("versionId", "19", FieldTypeError),
        ("templateSlug", 123, FieldTypeError),
        ("displayName", 123, FieldTypeError),
        ("manifest", ["not", "a", "dict"], FieldTypeError),
        ("manifestSha256", 12345, FieldTypeError),
        ("effectiveModelPolicy", "not-a-dict", FieldTypeError),
        ("revoked", "true", FieldTypeError),
        ("revoked", 1, FieldTypeError),
        ("revokedAt", 12345, FieldTypeError),
    ],
)
def test_wrong_field_type_rejected(field, bad_value, expected):
    payload = _base_payload(**{field: bad_value})
    with pytest.raises(expected) as exc_info:
        parse_runtime_assignment(payload)
    assert MANIFEST_CANARY not in str(exc_info.value)


@pytest.mark.parametrize("field", ["assignmentId", "revision", "templateId", "versionId"])
def test_bool_rejected_for_integer_fields(field):
    # bool is a subclass of int in Python; a JSON true/false is not a valid id.
    payload = _base_payload(**{field: True})
    with pytest.raises(FieldTypeError):
        parse_runtime_assignment(payload)


@pytest.mark.parametrize(
    "bad_sha",
    [
        "abc",
        "Z" * 64,  # non-hex, right length
        "A" * 64,  # uppercase rejected (project convention is lowercase)
    ],
)
def test_invalid_manifest_sha_format_rejected(bad_sha):
    payload = _base_payload(manifestSha256=bad_sha)
    with pytest.raises((FieldTypeError, ChecksumMismatchError)) as exc_info:
        parse_runtime_assignment(payload)
    assert MANIFEST_CANARY not in str(exc_info.value)


# --- effective-policy checksum: Java golden vectors ---------------------------


class TestPolicyChecksumGoldenVectors:
    """The parser must accept each Java-generated golden policy and surface the
    exact fixed SHA.  These SHAs come from SkillHub's PolicyChecksum.java, not
    from the Python framing function under test."""

    @pytest.mark.parametrize("vector", GOLDEN_VECTORS, ids=[v["id"] for v in GOLDEN_VECTORS])
    def test_golden_policy_parses_with_fixed_sha(self, vector):
        payload = _base_payload(effectiveModelPolicy=_golden_policy(vector))
        assignment = parse_runtime_assignment(payload)
        assert assignment.effective_model_policy["policySha256"] == vector["policySha256"]
        assert assignment.effective_model_policy["policyVersion"] == vector["policyVersion"]

    @pytest.mark.parametrize("vector", GOLDEN_VECTORS, ids=[v["id"] for v in GOLDEN_VECTORS])
    def test_golden_policy_version_is_sha_prefix(self, vector):
        assert vector["policyVersion"] == "sha256:" + vector["policySha256"][:12]

    def test_non_ascii_vector_uses_utf8_byte_length(self):
        """The non-ASCII golden vector proves the V framing counts UTF-8 bytes,
        not code points (中文模型 = 12 bytes, café = 5 bytes)."""
        vector = next(v for v in GOLDEN_VECTORS if v["id"] == "non_ascii_utf8_byte_length")
        assert "V23:enterprise/中文模型" in vector["framed"]
        assert "V16:enterprise/café" in vector["framed"]
        payload = _base_payload(effectiveModelPolicy=_golden_policy(vector))
        parse_runtime_assignment(payload)  # must not raise

    def test_java_test_cross_check_matches_skillhub_test_literal(self):
        """Cross-validates the harness against the literal SHA asserted by
        SkillHub's own EffectiveModelPolicyResolverTest."""
        vector = next(v for v in GOLDEN_VECTORS if v["id"] == "java_test_cross_check")
        assert vector["policySha256"] == (
            "c691e382c4f337ac5e93d492804200a4a4e1650cab6f11685556abeaef30901c"
        )


class TestPolicyChecksumFailures:
    def test_policy_sha_mismatch_raises_without_leaking(self):
        vector = GOLDEN_VECTORS[0]
        policy = _golden_policy(vector)
        policy["policySha256"] = "1" * 64  # valid format, wrong value
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(ChecksumMismatchError) as exc_info:
            parse_runtime_assignment(payload)
        assert POLICY_CANARY not in str(exc_info.value)

    def test_policy_version_mismatch_raises(self):
        vector = GOLDEN_VECTORS[0]
        policy = _golden_policy(vector)
        # policySha256 is correct, but policyVersion does not match its prefix.
        policy["policyVersion"] = "sha256:deadbeefdead"
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(ChecksumMismatchError) as exc_info:
            parse_runtime_assignment(payload)
        assert "policyversion" in str(exc_info.value).lower()

    def test_policy_version_not_sha_prefixed_rejected(self):
        vector = GOLDEN_VECTORS[0]
        policy = _golden_policy(vector)
        policy["policyVersion"] = "v1"  # legacy free-form version, no longer valid
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(ChecksumMismatchError):
            parse_runtime_assignment(payload)

    def test_missing_policy_sha256_rejected(self):
        policy = _golden_policy(GOLDEN_VECTORS[0])
        del policy["policySha256"]
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(MissingRequiredFieldError) as exc_info:
            parse_runtime_assignment(payload)
        assert POLICY_CANARY not in str(exc_info.value)

    def test_missing_policy_version_rejected(self):
        policy = _golden_policy(GOLDEN_VECTORS[0])
        del policy["policyVersion"]
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(MissingRequiredFieldError):
            parse_runtime_assignment(payload)

    def test_policy_sha_bad_format_rejected(self):
        policy = _golden_policy(GOLDEN_VECTORS[0])
        policy["policySha256"] = "not-hex"
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises((FieldTypeError, ChecksumMismatchError)) as exc_info:
            parse_runtime_assignment(payload)
        assert POLICY_CANARY not in str(exc_info.value)

    def test_allowed_models_order_changes_sha(self):
        """Reordering allowedModels must change the framed digest (list order
        is significant), so the original SHA no longer verifies."""
        vector = GOLDEN_VECTORS[1]  # has 2 allowed models
        policy = _golden_policy(vector)
        policy["allowedModels"] = list(reversed(policy["allowedModels"]))
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(ChecksumMismatchError):
            parse_runtime_assignment(payload)

    def test_fallback_models_order_changes_sha(self):
        vector = next(v for v in GOLDEN_VECTORS if v["id"] == "local_true")
        # Build a vector with 2 fallbacks by reusing allowed models as fallbacks.
        policy = _golden_policy(GOLDEN_VECTORS[1])
        policy["fallbackModels"] = ["enterprise/gpt-5"]
        # original vector[1] already has fallback [enterprise/gpt-5]; reverse is same.
        # Instead, append an extra fallback that is also allowed to force order sensitivity.
        policy["allowedModels"] = ["enterprise/deepseek-chat", "enterprise/gpt-5", "enterprise/extra"]
        policy["defaultModel"] = "enterprise/deepseek-chat"
        policy["fallbackModels"] = ["enterprise/gpt-5", "enterprise/extra"]
        # With this ordering the SHA will not match vector[1]'s golden SHA.
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(ChecksumMismatchError):
            parse_runtime_assignment(payload)

    def test_local_provider_bool_string_matters(self):
        """Flipping localProviderAllowed changes 'false'→'true' and the digest."""
        vector = GOLDEN_VECTORS[0]  # local=false
        policy = _golden_policy(vector)
        policy["localProviderAllowed"] = True
        payload = _base_payload(effectiveModelPolicy=policy)
        with pytest.raises(ChecksumMismatchError):
            parse_runtime_assignment(payload)

    def test_policy_field_type_errors(self):
        for field, bad in [
            ("mode", 123),
            ("allowedModels", "not-a-list"),
            ("allowedModels", [1, 2]),
            ("defaultModel", None),
            ("fallbackModels", "x"),
            ("localProviderAllowed", "true"),
        ]:
            policy = _golden_policy(GOLDEN_VECTORS[0])
            policy[field] = bad
            payload = _base_payload(effectiveModelPolicy=policy)
            with pytest.raises((FieldTypeError, MissingRequiredFieldError, ChecksumMismatchError)):
                parse_runtime_assignment(payload)


# --- manifest checksum (canonical JSON) ---------------------------------------


class TestManifestChecksum:
    def test_manifest_checksum_mismatch_raises_without_leaking(self):
        manifest = _base_manifest()
        payload = _base_payload(manifestSha256="0" * 64, manifest=manifest)
        with pytest.raises(ChecksumMismatchError) as exc_info:
            parse_runtime_assignment(payload)
        message = str(exc_info.value)
        assert MANIFEST_CANARY not in message
        assert sha256_hex(canonical_json_bytes(manifest)) not in message

    def test_manifest_tamper_after_correct_sha_detected(self):
        manifest = _base_manifest()
        good_sha = sha256_hex(canonical_json_bytes(manifest))
        tampered = {**manifest, "note": "tampered"}
        payload = _base_payload(manifest=tampered, manifestSha256=good_sha)
        with pytest.raises(ChecksumMismatchError):
            parse_runtime_assignment(payload)

    def test_manifest_and_policy_use_different_contracts(self):
        """The manifest digest (canonical JSON) must differ from any naive
        canonical-JSON digest of the policy — proving the two contracts are
        not conflated.  The policy golden SHA is NOT a canonical-JSON digest."""
        vector = GOLDEN_VECTORS[0]
        policy = {k: v for k, v in _golden_policy(vector).items() if k != "note"}
        canonical_policy_sha = sha256_hex(canonical_json_bytes(policy))
        assert canonical_policy_sha != vector["policySha256"]


class TestErrorHierarchy:
    def test_all_errors_are_managed_contract_errors(self):
        for exc in (
            MissingRequiredFieldError("x"),
            FieldTypeError("x"),
            ChecksumMismatchError("x"),
        ):
            assert isinstance(exc, ManagedContractError)
